[theme]
# Change the color of Buttons, Checkboxes, Sliders and active Tab line
primaryColor = "#236995"

# Change the background of main content area
backgroundColor = "#192036"

# Change the background of sidebar and input widgets
secondaryBackgroundColor = "#0c3a57"

# Change the text color
textColor = "#ffffff"

# Change the font style
font = "sans serif"

[client]
# Hide the deprecated warning specifically
showErrorDetails = false
showSidebarNavigation = true
